sharding:
  jdbc:
    datasource:
      names: db01,db02,db03
      db01:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://182.61.105.104:3307/Sharding-jdbc?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: root
        maxPoolSize: 20
      db02:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://182.61.105.104:3308/Sharding-jdbc?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: root
        maxPoolSize: 20
      db03:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://182.61.105.104:3309/Sharding-jdbc?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: root
        maxPoolSize: 20
    config:
      masterslave:
        load-balance-algorithm-type: round_robin  #\u8F6E\u8BE2\u7684\u8D1F\u8F7D\u5747\u8861\u65B9\u5F0F
        name: m1s2
        master-data-source-name: db01
        slave-data-source-names: db02,db03
      props:
        sql:
          show: true  #\u6253\u5370sql



spring:
  main:
    allow-bean-definition-overriding: true
